name: Release
permissions:
  contents: write

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.13'

      - name: Set up Node.js
        uses: actions/setup-node@v4.9.0
        with:
          node-version: '22'

      - name: Cache pip
        uses: actions/cache@v4.1.0
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml', '**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Node modules
        uses: actions/cache@v4.1.0
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node dependencies
        run: npm ci

      - name: Build (runs build.py)
        run: python build.py

      - name: List frontend dist
        run: ls -la frontend/dist

      - name: Smoke test
        run: ./dist/UnchainedLauncher --version

      - name: Create Linux artifact (zip)
        run: |
          cp -r dist/UnchainedLauncher ./UnchainedLauncher-linux
          zip -r unchainedlauncher-linux-${{ github.ref_name }}.zip UnchainedLauncher-linux

      - name: Upload artifact (for debugging)
        uses: actions/upload-artifact@v4.3.0
        with:
          name: unchainedlauncher-linux
          path: unchainedlauncher-linux-${{ github.ref_name }}.zip

  build-windows:
    name: Build (Windows)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11'

      - name: Set up Node.js
        uses: actions/setup-node@v4.9.0
        with:
          node-version: '20'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Node dependencies
        run: npm ci

      - name: Ensure npm is on PATH (diagnose)
        run: |
          where npm

      - name: Build (runs build.py)
        shell: pwsh
        run: python build.py

      - name: Smoke test
        shell: pwsh
        run: .\dist\UnchainedLauncher.exe --version

      - name: Package Windows exe
        shell: pwsh
        run: |
          Copy-Item "dist\UnchainedLauncher.exe" ".\UnchainedLauncher.exe" -Force
          Compress-Archive -Path .\UnchainedLauncher.exe -DestinationPath "unchainedlauncher-windows-${{ github.ref_name }}.zip" -Force

      - name: Upload artifact (for debugging)
        uses: actions/upload-artifact@v4.3.0
        with:
          name: unchainedlauncher-windows
          path: unchainedlauncher-windows-${{ github.ref_name }}.zip

  publish-release:
    name: Publish Release and Attach Artifacts
    needs: [build-linux, build-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Download Linux artifact
        uses: actions/download-artifact@v4.2.0
        with:
          name: unchainedlauncher-linux
          path: downloads

      - name: Download Windows artifact
        uses: actions/download-artifact@v4.2.0
        with:
          name: unchainedlauncher-windows
          path: downloads

      - name: Create GitHub Release and Upload Assets
        uses: softprops/action-gh-release@v1.28.0
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: "Release ${{ github.ref_name }} - built by CI"
          files: |
            downloads/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

